# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'local_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Change_Username(object):
    def setupUi(self, Change_Username):
        Change_Username.setObjectName("Change_Username")
        Change_Username.resize(400, 300)
        Change_Username.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.545, cy:0.0568182, radius:1.39, fx:0.528249, fy:0.33, stop:0.431818 rgba(56, 56, 56, 255), stop:1 rgba(75, 75, 75, 255));\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Change_Username)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Change_Username)
        self.label.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"border: 2px solid rgb(0, 0, 0);\n"
"color: rgb(6, 205, 227);\n"
"background-color: rgb(56, 56, 56);")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(Change_Username)
        self.lineEdit.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"border: 2px solid rgb(0, 0, 0);\n"
"color: rgb(5, 153, 167);\n"
"background-color: rgb(156, 156, 156);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Change_Username)
        self.buttonBox.setStyleSheet("QPushButton\n"
"                             {\n"
"                            background-color: qlineargradient(spread:pad, x1:0.511, y1:0.727,         x2:0.528, y2:0, stop:0.431818 rgba(31, 31, 31, 255), stop:1 rgba(75, 75, 75, 255));\n"
"font: 20pt \"High Tower Text\";\n"
"color: rgb(6, 205, 227);\n"
"border: 1px solid rgb(6, 205, 227);\n"
"                             }\n"
"                             QPushButton::hover {\n"
"                            \n"
"background-color: qradialgradient(spread:pad, cx:0.545, cy:0.0568182, radius:1.39, fx:0.528249, fy:0.33, stop:0.420455 rgba(75, 75, 75, 255), stop:1 rgba(56, 56, 56, 255));\n"
"}\n"
"\n"
"\n"
"                             QPushButton::pressed\n"
"                             {\n"
"                             \n"
"    background-color: qradialgradient(spread:pad, cx:0.545, cy:0.0568182, radius:1.39, fx:0.528249, fy:0.33, stop:0.431818 rgba(110, 110, 110, 255), stop:1 rgba(99, 99, 99, 255));\n"
"                             }\n"
"\n"
"")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 1, 1, 1)

        self.retranslateUi(Change_Username)
        self.buttonBox.accepted.connect(Change_Username.accept)
        self.buttonBox.rejected.connect(Change_Username.reject)
        QtCore.QMetaObject.connectSlotsByName(Change_Username)

    def retranslateUi(self, Change_Username):
        _translate = QtCore.QCoreApplication.translate
        Change_Username.setWindowTitle(_translate("Change_Username", "Change Username"))
        self.label.setText(_translate("Change_Username", "Username"))
