# CMake generated Testfile for 
# Source directory: /home/filipjanuska/Desktop/IVS_Projekt_1/assignment
# Build directory: /home/filipjanuska/Desktop/IVS_Projekt_1
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(EmptyTree.InsertNode "/home/filipjanuska/Desktop/IVS_Projekt_1/black_box_test" "--gtest_filter=EmptyTree.InsertNode")
set_tests_properties(EmptyTree.InsertNode PROPERTIES  _BACKTRACE_TRIPLES "/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/GoogleTest.cmake;39;add_test;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;32;GTEST_ADD_TESTS;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;0;")
add_test(EmptyTree.DeleteNode "/home/filipjanuska/Desktop/IVS_Projekt_1/black_box_test" "--gtest_filter=EmptyTree.DeleteNode")
set_tests_properties(EmptyTree.DeleteNode PROPERTIES  _BACKTRACE_TRIPLES "/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/GoogleTest.cmake;39;add_test;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;32;GTEST_ADD_TESTS;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;0;")
add_test(EmptyTree.FindNode "/home/filipjanuska/Desktop/IVS_Projekt_1/black_box_test" "--gtest_filter=EmptyTree.FindNode")
set_tests_properties(EmptyTree.FindNode PROPERTIES  _BACKTRACE_TRIPLES "/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/GoogleTest.cmake;39;add_test;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;32;GTEST_ADD_TESTS;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;0;")
add_test(NonEmptyTree.InsertNode "/home/filipjanuska/Desktop/IVS_Projekt_1/black_box_test" "--gtest_filter=NonEmptyTree.InsertNode")
set_tests_properties(NonEmptyTree.InsertNode PROPERTIES  _BACKTRACE_TRIPLES "/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/GoogleTest.cmake;39;add_test;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;32;GTEST_ADD_TESTS;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;0;")
add_test(NonEmptyTree.DeleteNode "/home/filipjanuska/Desktop/IVS_Projekt_1/black_box_test" "--gtest_filter=NonEmptyTree.DeleteNode")
set_tests_properties(NonEmptyTree.DeleteNode PROPERTIES  _BACKTRACE_TRIPLES "/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/GoogleTest.cmake;39;add_test;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;32;GTEST_ADD_TESTS;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;0;")
add_test(NonEmptyTree.FindNode "/home/filipjanuska/Desktop/IVS_Projekt_1/black_box_test" "--gtest_filter=NonEmptyTree.FindNode")
set_tests_properties(NonEmptyTree.FindNode PROPERTIES  _BACKTRACE_TRIPLES "/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/GoogleTest.cmake;39;add_test;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;32;GTEST_ADD_TESTS;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;0;")
add_test(TreeAxioms.Axiom1 "/home/filipjanuska/Desktop/IVS_Projekt_1/black_box_test" "--gtest_filter=TreeAxioms.Axiom1")
set_tests_properties(TreeAxioms.Axiom1 PROPERTIES  _BACKTRACE_TRIPLES "/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/GoogleTest.cmake;39;add_test;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;32;GTEST_ADD_TESTS;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;0;")
add_test(TreeAxioms.Axiom2 "/home/filipjanuska/Desktop/IVS_Projekt_1/black_box_test" "--gtest_filter=TreeAxioms.Axiom2")
set_tests_properties(TreeAxioms.Axiom2 PROPERTIES  _BACKTRACE_TRIPLES "/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/GoogleTest.cmake;39;add_test;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;32;GTEST_ADD_TESTS;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;0;")
add_test(TreeAxioms.Axiom3 "/home/filipjanuska/Desktop/IVS_Projekt_1/black_box_test" "--gtest_filter=TreeAxioms.Axiom3")
set_tests_properties(TreeAxioms.Axiom3 PROPERTIES  _BACKTRACE_TRIPLES "/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/GoogleTest.cmake;39;add_test;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;32;GTEST_ADD_TESTS;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;0;")
add_test(Initial.construct "/home/filipjanuska/Desktop/IVS_Projekt_1/white_box_test" "--gtest_filter=Initial.construct")
set_tests_properties(Initial.construct PROPERTIES  _BACKTRACE_TRIPLES "/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/GoogleTest.cmake;39;add_test;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;36;GTEST_ADD_TESTS;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;0;")
add_test(Matica.set "/home/filipjanuska/Desktop/IVS_Projekt_1/white_box_test" "--gtest_filter=Matica.set")
set_tests_properties(Matica.set PROPERTIES  _BACKTRACE_TRIPLES "/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/GoogleTest.cmake;39;add_test;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;36;GTEST_ADD_TESTS;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;0;")
add_test(Matica.set_vector "/home/filipjanuska/Desktop/IVS_Projekt_1/white_box_test" "--gtest_filter=Matica.set_vector")
set_tests_properties(Matica.set_vector PROPERTIES  _BACKTRACE_TRIPLES "/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/GoogleTest.cmake;39;add_test;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;36;GTEST_ADD_TESTS;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;0;")
add_test(Matica.get "/home/filipjanuska/Desktop/IVS_Projekt_1/white_box_test" "--gtest_filter=Matica.get")
set_tests_properties(Matica.get PROPERTIES  _BACKTRACE_TRIPLES "/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/GoogleTest.cmake;39;add_test;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;36;GTEST_ADD_TESTS;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;0;")
add_test(Matica.compare "/home/filipjanuska/Desktop/IVS_Projekt_1/white_box_test" "--gtest_filter=Matica.compare")
set_tests_properties(Matica.compare PROPERTIES  _BACKTRACE_TRIPLES "/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/GoogleTest.cmake;39;add_test;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;36;GTEST_ADD_TESTS;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;0;")
add_test(Matica.add "/home/filipjanuska/Desktop/IVS_Projekt_1/white_box_test" "--gtest_filter=Matica.add")
set_tests_properties(Matica.add PROPERTIES  _BACKTRACE_TRIPLES "/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/GoogleTest.cmake;39;add_test;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;36;GTEST_ADD_TESTS;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;0;")
add_test(Matica.multiply_matrix "/home/filipjanuska/Desktop/IVS_Projekt_1/white_box_test" "--gtest_filter=Matica.multiply_matrix")
set_tests_properties(Matica.multiply_matrix PROPERTIES  _BACKTRACE_TRIPLES "/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/GoogleTest.cmake;39;add_test;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;36;GTEST_ADD_TESTS;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;0;")
add_test(Matica.multiply_scalar "/home/filipjanuska/Desktop/IVS_Projekt_1/white_box_test" "--gtest_filter=Matica.multiply_scalar")
set_tests_properties(Matica.multiply_scalar PROPERTIES  _BACKTRACE_TRIPLES "/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/GoogleTest.cmake;39;add_test;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;36;GTEST_ADD_TESTS;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;0;")
add_test(Matica.solve "/home/filipjanuska/Desktop/IVS_Projekt_1/white_box_test" "--gtest_filter=Matica.solve")
set_tests_properties(Matica.solve PROPERTIES  _BACKTRACE_TRIPLES "/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/GoogleTest.cmake;39;add_test;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;36;GTEST_ADD_TESTS;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;0;")
add_test(NonEmptyQueue.Insert "/home/filipjanuska/Desktop/IVS_Projekt_1/tdd_test" "--gtest_filter=NonEmptyQueue.Insert")
set_tests_properties(NonEmptyQueue.Insert PROPERTIES  _BACKTRACE_TRIPLES "/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/GoogleTest.cmake;39;add_test;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;43;GTEST_ADD_TESTS;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;0;")
add_test(NonEmptyQueue.RemoveAllForward "/home/filipjanuska/Desktop/IVS_Projekt_1/tdd_test" "--gtest_filter=NonEmptyQueue.RemoveAllForward")
set_tests_properties(NonEmptyQueue.RemoveAllForward PROPERTIES  _BACKTRACE_TRIPLES "/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/GoogleTest.cmake;39;add_test;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;43;GTEST_ADD_TESTS;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;0;")
add_test(NonEmptyQueue.RemoveAllBackward "/home/filipjanuska/Desktop/IVS_Projekt_1/tdd_test" "--gtest_filter=NonEmptyQueue.RemoveAllBackward")
set_tests_properties(NonEmptyQueue.RemoveAllBackward PROPERTIES  _BACKTRACE_TRIPLES "/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/GoogleTest.cmake;39;add_test;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;43;GTEST_ADD_TESTS;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;0;")
add_test(NonEmptyQueue.Find "/home/filipjanuska/Desktop/IVS_Projekt_1/tdd_test" "--gtest_filter=NonEmptyQueue.Find")
set_tests_properties(NonEmptyQueue.Find PROPERTIES  _BACKTRACE_TRIPLES "/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/GoogleTest.cmake;39;add_test;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;43;GTEST_ADD_TESTS;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;0;")
add_test(EmptyQueue.Insert "/home/filipjanuska/Desktop/IVS_Projekt_1/tdd_test" "--gtest_filter=EmptyQueue.Insert")
set_tests_properties(EmptyQueue.Insert PROPERTIES  _BACKTRACE_TRIPLES "/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/GoogleTest.cmake;39;add_test;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;43;GTEST_ADD_TESTS;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;0;")
add_test(EmptyQueue.Remove "/home/filipjanuska/Desktop/IVS_Projekt_1/tdd_test" "--gtest_filter=EmptyQueue.Remove")
set_tests_properties(EmptyQueue.Remove PROPERTIES  _BACKTRACE_TRIPLES "/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/GoogleTest.cmake;39;add_test;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;43;GTEST_ADD_TESTS;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;0;")
add_test(EmptyQueue.Find "/home/filipjanuska/Desktop/IVS_Projekt_1/tdd_test" "--gtest_filter=EmptyQueue.Find")
set_tests_properties(EmptyQueue.Find PROPERTIES  _BACKTRACE_TRIPLES "/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/GoogleTest.cmake;39;add_test;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;43;GTEST_ADD_TESTS;/home/filipjanuska/Desktop/IVS_Projekt_1/assignment/CMakeLists.txt;0;")
subdirs("googletest-build")
