############################################################
#		   Makefile pre IOS proj2		   #
#		Autor: Filip Januska, xjanus11		   #
#		   FIT VUT Brno 2019/2020		   #
###########################################################

CC=gcc
CFLAGS= -std=gnu99 -Wall -Wextra -Werror -pedantic -lpthread -lrt

all: proj2

proj2: proj2.c
	$(CC) $(CFLAGS) -o proj2 proj2.c
